### PR TITLE
modularize the code

### PR DESCRIPTION
**Pull request by mreinstein**
#1 

* modularize the code
* switch to es6
* produce minified builds
* allow the visualizer to accept more options (mediaStream, parent container.)
* allow the visualizer to be attached to other things besides the window object (e.g., embedding the visualizations in a div)
* slight performance improvements
* make the visualizations display properly on retina (macbook, ios) screens

### CODE REVIEW

**Comment by mreinstein** [comment]
@ianharmon would love any feedback on this.

thoughts on releasing this under MIT licensing?

**Comment by ianharmon** [comment]
MIT sounds good, I can probably take a look at the changes after work

**Comment by ianharmon** [comment]
This is more extensive than I'm comfortable maintaining (although I've written stuff in Node, I don't use it often), but I went ahead and made the repo MIT-licensed, so you're free to take the lead on an updated version.

BTW, I realized that the version here on GitHub was a version out of date vs. what I had on my PC/website, but I think the only major changes there were the addition of two 3D visualizations, Sphere and Mountain. They use a separate canvas and Three.js.

Then tonight I was looking at the Image visualization and scratching my head a bit at my logic (there's unused variables, and the greyscale -> spectrum conversion didn't really make sense), so I revamped that a bit. I did make some additional small changes here and there since the repo hasn't been touched in 2+ years, but you've probably covered the important structural parts.

**Comment by mreinstein** [comment]
> This is more extensive than I'm comfortable maintaining

Definitely don't feel that you have to include these changes. One of my clients decided to use your visualizations, and they look nice. But it was hard to use these in a modular way (hard to build large and reasonable javascript apps with many global variables.)

I recognize that these changes do introduce some overhead in building the code, and add a dependency on node/npm. If it's more burden then and overhead than you're willing to accept don't feel like you must incorporate them.  Just let me know and I'll maintain my own libraries specifically for this customer.

**Comment by ianharmon** [comment]
Sounds good, and that's cool to hear it got used in a project. Also, I added a link in the readme to your fork

**Pull request closed without merging**
